spring:
  cloud:
    function:
      definition: consumeMessage
    stream:
      default:
        consumer:
          retryable-exceptions:
            java.lang.ArrayIndexOutOfBoundsException: true
            org.hibernate.exception.DataException: true
            java.lang.ArithmeticException: false
            java.lang.ArithmeticException2: false
      kafka:
        binder:
          transaction:
            transaction-id-prefix: transaction-
          required-acks: all
          configuration:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        bindings:
          consumeMessage-in-0:
            consumer:
              enable-dlq: true
      bindings:
        consumeMessage-in-0:
          group: my-group
          destination: my-topic
          consumer:
            default-retryable: false
            max-attempts: 5
            back-off-initial-interval: 100
            retryable-exceptions:
              java.lang.UnsupportedOperationException: true
              java.lang.IllegalArgumentException: false
